### ISSUE TITLE
I want to know what the results generated after the training are

### ISSUE THREAD

**Issue by anshanYCL** [ziyc/drivestudio#10]
Great functionality! What is the result after completing the training? Is it a traditional 3DGS ply file? Or is it some other file?

**Comment by anshanYCL** [comment]
sorry
another question：What is required for inputting data? Image? Point cloud? Pose file? Or something else?

**Comment by WuZhongQing** [comment]
i have the same question

**Comment by ziyc** [comment]
Hi @WuZhongQing @anshanYCL, thanks for your interest.

> What is the result after completing the training? Is it a traditional 3DGS ply file? Or is it some other file?

Currently, the output is checkpoint that contains Gaussian parameters, processed like this:
https://github.com/ziyc/drivestudio/blob/388642a6a998833cb388e0f1a65dfc2071cc6a61/models/gaussians/vanilla.py#L454-L463

This differs from the traditional 3DGS ply file. But I agree it would be beneficial to also export in the traditional ply format. Thank you for bringing this to my attention, I'll incorporate this feature in the near future.

> What is required for inputting data? Image? Point cloud? Pose file? Or something else?

For both static and dynamic scenes, the input requirements are images, poses, and LiDAR data. For dynamic scenes, we additionally need object bounding boxes.

**Comment by iwander-all** [comment]
Hello, how to find and visualize the output, thanks.
