### ISSUE TITLE
Issue with evaluation

### ISSUE THREAD

**Issue by GopiRajuMatta** [ziyc/drivestudio#14]
Hello @ziyc

Thank you for open sourcing great work..

There is an issue with evaluation, we are having 64GB RAM with two sets of 24GB NVIDIA RTX 3090 GPUs. While running evaluation script, around 20% of execution, process is getting killed by itself. 

Do you have any suggestion(s) to make this run without this issue?

Thank you
Gopi

**Comment by MatteoMarengo** [comment]
I have the same issue but with training gsplat is killing itself. How to reduce the MAX JOBS ?

**Comment by ziyc** [comment]
Hi @GopiRajuMatta @MatteoMarengo, 

How many images are you trying to train with? This issue might occur when the sequence is extremely long (e.g., training with 7 cameras, each having 300 frames).

Please refer to #5, as it seems to be the same issue. 

I'll try to optimize the logging module to avoid excessive RAM consumption once I get through this busy period in the next couple of weeks. Thank you for your understanding and patience.
