### ISSUE TITLE
NaN occ in the training time

### ISSUE THREAD

**Issue by happyxuwork** [ziyc/drivestudio#16]
fellow the Waymo.md, prepare the dataset and running env
start trainning use command as fellow:
 python tools/train.py --config_file configs/omnire.yaml dataset=waymo/1cams data.scene_idx=23 data.start_timestep=0 data.end_timestep=-1
but NaN occ when training as fellow:
![image](https://github.com/user-attachments/assets/33035469-d9ec-4708-8ed6-76985cc3f611)

**Comment by ziyc** [comment]
Hi @happyxuwork,

Thanks for reporting this. I'm tied up for the next two days, but could you please try commenting out these lines:
https://github.com/ziyc/drivestudio/blob/388642a6a998833cb388e0f1a65dfc2071cc6a61/configs/omnire.yaml#L80-L84

Then re-run and see if that helps? I'll be back in two days to investigate further.

Appreciate your understanding!

**Comment by happyxuwork** [comment]
@ziyc comment out lines and re-run, but other error occ as fellow:
![image](https://github.com/user-attachments/assets/57eda8e0-149d-4aa2-ab24-47f7889500df)

**Comment by ziyc** [comment]
Hi @fy2462, does the same issue occurs if you train on other sequences? It might due to dataoverflow, can you try replacing

```
reg: 
   sharp_shape_reg: 
     w: 1. 
     step_interval: 10 
     max_gauss_ratio: 10.  
```

with 

```
reg: 
   sharp_shape_reg: null
```

only do this for Background, because the NaN is detect in bg gaussians.

I'll give it more investigation these days, thanks for your patience.
