### ISSUE TITLE
Modify MAX_JOBS parameter

### ISSUE THREAD

**Issue by MatteoMarengo** [ziyc/drivestudio#17]
Hi,

How to modify MAX_JOBS parameter so it is not 10 anymore when running gsplat ?
Thanks !

**Comment by ziyc** [comment]
@MatteoMarengo Can you share a screenshot or output to help locate the issue?

**Comment by MatteoMarengo** [comment]
@ziyc 

for sure

![issue](https://github.com/user-attachments/assets/4ce60262-ae30-4dad-ae30-b8558c77e9ff)

**Comment by ziyc** [comment]
It seems that you installed `gsplat` with pip, this way requires compilation for the first run. I recommend using `pip install git+https://github.com/nerfstudio-project/gsplat.git@v1.3.0` to install gsplat

**Comment by MatteoMarengo** [comment]
No I have installed gsplat with your method (I have rerun the command line to be certain) and I still have the same error, would you see any points where I can downgrade the required requirements for example ?

my command line is this one:

python tools/train.py --config_file configs/omnire.yaml --output_root $output_root --project $project --run_name $expname dataset=nuscenes/6cams data.scene_idx=$scene_idx data.start_timestep=$start_timestep data.end_timestep=$end_timestep seed=31

**Comment by ziyc** [comment]
Is this happening with all scenes or just the one you showed? If it's all scenes, it might be an environment issue. Can you share your GPU type and CUDA version? 

Also, what values did you use for scene_idx, start_timestep, and end_timestep in your command? These are just placeholders, what's the actual value?

**Comment by ziyc** [comment]
Can you try the [examples of gsplat](https://github.com/nerfstudio-project/gsplat?tab=readme-ov-file#examples) to check if  gsplat can successfully run on your device or env?

**Comment by MatteoMarengo** [comment]
It now works better, the issue was coming from not enough CPU Ram, it is now better with an increased value.
