### ISSUE TITLE
Background in the training

### ISSUE THREAD

**Issue by MatteoMarengo** [ziyc/drivestudio#18]
How do you deal with the background in the training part ? For example in gsplat, in simple_trainer.py it is used like that:

           if cfg.random_bkgd:
                bkgd = torch.rand(1, 3, device=device)
                colors = colors + bkgd * (1.0 - alphas)

**Comment by ziyc** [comment]
Hi @MatteoMarengo, I think you're asking about how we handled the sky color, please refer to here:

https://github.com/ziyc/drivestudio/blob/388642a6a998833cb388e0f1a65dfc2071cc6a61/models/trainers/base.py#L490-L493
