### ISSUE TITLE
Installation Error for Gsplat

### ISSUE THREAD

**Issue by FudongGe** [ziyc/drivestudio#19]
When trying to "pip install git+https://github.com/nerfstudio-project/gsplat.git@v1.3.0", I meet this problem. Did someone know how to fix it?

![image](https://github.com/user-attachments/assets/561d55c6-6240-4fa8-8ade-55e0eb4d4e7a)

**Comment by ziyc** [comment]
Hi @FudongGe,

This might be a CUDA-PyTorch version mismatch. Have you installed the correct PyTorch version for your CUDA? We support `gsplat>=1.0.0`. You can check the [gsplat repo](https://github.com/nerfstudio-project/gsplat) for similar issues and solutions.

I hope this response is helpful. If you have more questions, feel free to ask.

**Comment by FudongGe** [comment]
> Hi @FudongGe,
> 
> This might be a CUDA-PyTorch version mismatch. Have you installed the correct PyTorch version for your CUDA? We support `gsplat>=1.0.0`. You can check the [gsplat repo](https://github.com/nerfstudio-project/gsplat) for similar issues and solutions.
> 
> I hope this response is helpful. If you have more questions, feel free to ask.

Hi, Ziyu.

Thanks for your response.

Actually, I follow your installation guide and install torch==2.0.0+cu117. My CUDA toolkit version is 11.7, and my CUDA driver can support up to 12.2. I don't think this will lead to version conflicts. Do you have any other ideas？

![image](https://github.com/user-attachments/assets/8160dc0f-bcc0-46af-9aa0-c8ecf91d16b0)
![image](https://github.com/user-attachments/assets/e1978b19-deb5-4ccf-85bd-088859d399ad)

**Comment by ziyc** [comment]
emmmm, it's strange, can you try `pip install gsplat==1.3.0` and just run? If it doesn't work, you could try other versions like `pip install gsplat==1.0.0`, if it still got error, feel free to show it to me.

**Comment by FudongGe** [comment]
> emmmm, it's strange, can you try `pip install gsplat==1.3.0` and just run? If it doesn't work, you could try other versions like `pip install gsplat==1.0.0`, if it still got error, feel free to show it to me.

Yes, direct 'pip install gsaplt==1.3.0' is ok. But about whether it can run successfully, I will try. Thanks. 
By the way, what's the difference between the two installation methods ? Thanks again!

![image](https://github.com/user-attachments/assets/68e57f31-a4d1-4334-9dff-00067d7fba6b)

**Comment by ziyc** [comment]
Hi @FudongGe, these two ways determine when the lib is compiled. As described here:

![image](https://github.com/user-attachments/assets/19cc0920-618e-4707-8b2d-60f077f92e86)

**Comment by FudongGe** [comment]
> Hi @FudongGe, these two ways determine when the lib is compiled. As described here:
> 
> ![image](https://private-user-images.githubusercontent.com/49823897/367628149-19cc0920-618e-4707-8b2d-60f077f92e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzU3NjEsIm5iZiI6MTcyNjQ3NTQ2MSwicGF0aCI6Ii80OTgyMzg5Ny8zNjc2MjgxNDktMTljYzA5MjAtNjE4ZS00NzA3LThiMmQtNjBmMDc3ZjkyZTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4MzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZTEyMTNlZjg1NzJkMjE4MTdhMTdkOGQ5MTU5MjhkMzI5MTdjNjVkYTllNTEyNjQ3NDM5NTVmMWQzYWFjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjyvDARhq8AQZb-TvKjdZNZbQ3zHu0u78ODbl9txfPs)

Thanks very much！
