### ISSUE TITLE
Adding New foreground moving objects

### ISSUE THREAD

**Issue by Wastoon** [ziyc/drivestudio#21]
真是非常棒的工作，想请问的是：如果我们已经在一个固定场景中训练完成了模型，在eval阶段使用训练得到的checkpoint可以向这个场景中增加更多的前景物体吗？这些新增的前景模型渲染到相机里面时，还是借助Gaussian Splatting吗？就像您在项目网站上公开的Pedestrians Dreamer，想要新增和替换前景物体，是借助mesh另行渲染？还是说借助Gaussian Splatting就可以新增或者修改编辑场景中的前景物体呢？盼复，万分感谢。

![image](https://github.com/user-attachments/assets/e051c97b-7b4e-48ec-b3dd-b98b9a904112)

**Comment by ziyc** [comment]
Hi @Wastoon, all demos shown on our project page are rendered solely using Gaussian Splatting. We didn't use any other rendering techniques.

The goal of adding/replacing/editing/removing foreground objects can be achieved just by using Gaussian Splatting.

Hope this answer is helpful!

**Comment by ziyc** [comment]
If you're interested in how the editing is achieved, please refer to the discussion in #4. It might be useful to you.

**Comment by Wastoon** [comment]
感谢回复，真的很棒

**Comment by Wastoon** [comment]
> If you're interested in how the editing is achieved, please refer to the discussion in #4. It might be useful to you.

作者你好呀，我仔细查看了issue#4，对于在已有的场景中新增前景物体还是有一些疑问，希望您能帮忙解答一下。1. 如果我们想要在一个已经训练好的场景的3DGS模型中增加物体，需要重新训练模型吗？因为这些新增加物体的gs node的mean, color,, 我们都可以得到，但是这些物体的opacities和scale却只能被初始化成虚假的初值，所以就比较困惑，是不是在一个训练好模型的场景中新增物体是不是需要重新训练模型？2. 书接上文，如果需要重新训练模型的话，那新增加前景物体在目标camera中的RGB和depth真值您是怎么获得的呢？

**Comment by zzz5y** [comment]
> > If you're interested in how the editing is achieved, please refer to the discussion in #4. It might be useful to you.
> 
> 作者你好呀，我仔细查看了issue#4，对于在已有的场景中新增前景物体还是有一些疑问，希望您能帮忙解答一下。1. 如果我们想要在一个已经训练好的场景的3DGS模型中增加物体，需要重新训练模型吗？因为这些新增加物体的gs node的mean, color,, 我们都可以得到，但是这些物体的opacities和scale却只能被初始化成虚假的初值，所以就比较困惑，是不是在一个训练好模型的场景中新增物体是不是需要重新训练模型？2. 书接上文，如果需要重新训练模型的话，那新增加前景物体在目标camera中的RGB和depth真值您是怎么获得的呢？

您好呀，能请问一下您对这个1 2问题 的思路吗！非常感谢
