### ISSUE TITLE
how to edit the scene

### ISSUE THREAD

**Issue by happyxuwork** [ziyc/drivestudio#29]
When one video is complete train and gets the xx.pth, how generate a novel view video?  For example , how to achieve the effect of camera shake?  Directly edit the camera's intrinsic and extrinsic parameters？

**Comment by zzz5y** [comment]
I wonder it too.Can you share wiht me if you know

**Comment by ziyc** [comment]
Hi @happyxuwork @zzz5y,

I find this question is similar to #31. Please refer to that issue for more information. I hope it is helpful.
