### ISSUE TITLE
Issue with smplx env dependency

### ISSUE THREAD

**Issue by fgz-ai** [ziyc/drivestudio#3]
Thank you for sharing your excellent work!

It appears that the provided **smpl.pkl** files for NuScenes (v1.0-mini split) are not compatible with **[data_struct](https://github.com/ziyc/drivestudio/blob/b134d801054645da9bb944877fce12d7875af13c/third_party/smplx/smplx/body_models.py#L158)**.

Have you tested the code with the provided human pose data for NuScenes, or am I missing something?

**Comment by ziyc** [comment]
Hi @fgz-ai , I modified the issue title a bit since its not related to the pre-processed smpl files, but result from the env packages version mismatching, for which I've updated the env dependencies, I've tested it and it's bug-free now.

**Comment by MatteoMarengo** [comment]
@fgz-ai did you manage to solve the issue ? Did you reinstall the env ?
Was your error :
  drivestudio/third_party/smplx/smplx/body_models.py", line 155, in __init__
    assert osp.exists(smpl_path), "Path {} does not exist!".format(smpl_path)
AssertionError: Path smpl_models/SMPL_NEUTRAL.pkl does not exist!

?
Thank you

**Comment by fgz-ai** [comment]
@MatteoMarengo, 
It has been explained in [Prerequisites](https://github.com/ziyc/drivestudio/blob/main/docs/HumanPose.md#prerequisites) 
You may find .pkl files [here](https://huggingface.co/spaces/brjathu/HMR2.0/tree/e5201da358ccbc04f4a5c4450a302fcb9de571dd/data/smpl).
