### ISSUE TITLE
imperfect dynamic object reconstruction

### ISSUE THREAD

**Issue by szhang963** [ziyc/drivestudio#40]
Hi, thanks for your great work.
I have used my dataset in drivestudio. However, I got some bad results.
- First, the dynamic object reconstruction failed in the red box.
![image](https://github.com/user-attachments/assets/2e96e6d4-80ac-44a8-baa4-9d26f943781a)
- Second, the background is blurred in the red box.
![image](https://github.com/user-attachments/assets/ce579d22-103f-4049-a3a5-4ac50c8d74ce)

I would appreciate it if you can give me some guidance.
Best wishes.

**Comment by KMnO4AndWaston** [comment]
> Hi, thanks for your great work. I have used my dataset in drivestudio. However, I got some bad results.
> 
> * First, the dynamic object reconstruction failed in the red box.
>   ![image](https://private-user-images.githubusercontent.com/38983719/374965113-2e96e6d4-80ac-44a8-baa4-9d26f943781a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODIxMTUsIm5iZiI6MTczMDA4MTgxNSwicGF0aCI6Ii8zODk4MzcxOS8zNzQ5NjUxMTMtMmU5NmU2ZDQtODBhYy00NGE4LWJhYTQtOWQyNmY5NDM3ODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMmZkZjEyOTZhNTY0N2M1MzNlNzcxNDY1NWE3OTA1YjhjYzcxNjkxZWUzMTRiMTE0NjZiZjkyNTcxNDVjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1y4amR9SIE18PAgtO-UCQbB3g29HIJbB6PSmVydsuiE)
> * Second, the background is blurred in the red box.
>   ![image](https://private-user-images.githubusercontent.com/38983719/374969264-ce579d22-103f-4049-a3a5-4ac50c8d74ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODIxMTUsIm5iZiI6MTczMDA4MTgxNSwicGF0aCI6Ii8zODk4MzcxOS8zNzQ5NjkyNjQtY2U1NzlkMjItMTAzZi00MDQ5LWEzYTUtNGFjNTBjOGQ3NGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YjA3Zjg3M2FkOTE1MmIzNmMxMzBiYmVjMTUzOTQ2MGM1NmFiZGExMDNlZGI2ZDM2MGQyZDEyZjE5ZThmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RDdhzDvaowdW80ye1EpXIZ_TQQKQcY0xXbchI5D1ACo)
> 
> I would appreciate it if you can give me some guidance. Best wishes.

Hello, I met the same problem just like you, the background is not very good when use multi-cam. Have you solved the problem?

**Comment by jerryr1c** [comment]
Hello，same to me, the background is not very good when use multi-cam. Have you guys solved the problem or any ideas to solve the problems?

**Comment by Wastoon** [comment]
> Hello，same to me, the background is not very good when use multi-cam. Have you guys solved the problem or any ideas to solve the problems?

Try to decrease learning rate of optim xyz........
