### ISSUE TITLE
Do i need to retrain when I edit the rigid nodes?

### ISSUE THREAD

**Issue by zzz5y** [ziyc/drivestudio#42]
Thanks for you excellent work and sorry for my dumb questions!

I would like to know under what conditions editing a scene would require retraining. I’ve found that if I need to delete a rigid node, retraining is necessary, but if I’m only controlling the camera trajectory, then I only need to rerender. However, if I need to rotate a vehicle, would that require retraining? What if rigid nodes are being replaced with each other? Similarly, if I need to change instances_quats and instances_trans to control the trajectory of the rigid nodes, would retraining be required

**Comment by zzz5y** [comment]
sorry for my stupid problem! it's not necessary! just edit the scene in do_evaluation(In my opinion,not 100% correct!

**Comment by zohairbadshah** [comment]
@zzz5y can editing be done without retraining, if yes then how?
