### ISSUE TITLE
On generating masks with bounding boxes

### ISSUE THREAD

**Issue by Enamel2** [ziyc/drivestudio#44]
Thanks for the excellent and inspiring work! If I may, I would like to ask a little question I encountered when I writing my own preprocess script.

I noticed the dynamic mask generation process will exclude partially visible objects, so that image region of those partially visible dynamic objects will not have a mask on them. Would this pollute the training for the background GS model? Or am I missing something?

Thanks a lot for your time answering my question!

**Comment by ziyc** [comment]
Hi @Enamel2, thanks for your question! 

The dynamic masks are only used when evaluating the trained results - we use them to mask dynamic regions and compute metrics specifically for those areas. While the dynamic mask processing may occasionally have prediction errors from the masking models, it's tolerable and it doesn't affect the training process. During training, we only use sky masks for sky supervision.

**Comment by Enamel2** [comment]
Thank you for the elaborated explanation! This helps a lot!
