### ISSUE TITLE
A question about SMPLNodes_rgb

### ISSUE THREAD

**Issue by xiao1874** [ziyc/drivestudio#46]
hi,I'm trying to experiment with my own dataset and I'm finding that the SMPLNodes_rgb in the rendered results don't seem to be as expected and distorted.(fig 1). Can you give some advice?
When I was making the humanpose data, I could see the correct pose result in temp/phalp_output/PHALP_0.mp4 (fig 2), and the pedestrians rendered in DeformableNodes were also normal (fig 3).

fig 1
![step_0_SMPLNodes_rgbs](https://github.com/user-attachments/assets/f95b81fd-1972-4cb0-a53f-504cbfba7862)
fig 2
![Screenshot from 2024-10-17 17-34-29](https://github.com/user-attachments/assets/0afa24e9-b56d-41d0-b1e9-0204c16441a1)
fig 3
![step_0_DeformableNodes_rgbs](https://github.com/user-attachments/assets/930ee95f-f5d2-4498-bdbd-0fe0f2199e35)

**Comment by ziyc** [comment]
Hi, @xiao1874, from the figures you shared, this appears to be a coordinate convention mismatch. Since the poses look correct in PHALP output and DeformableNodes rendering, you may want to check if your SMPLNodes' convention matches the expected one.

**Comment by xiao1874** [comment]
thx! I have successfully solved the problem!

**Comment by zzz5y** [comment]
@xiao1874  Hello,I am trying to use my custom dataset ,Could you give some suggestions about  handing the coordinate system on sourceloder part and project_human_boxes function?

**Comment by xiao1874** [comment]
> @xiao1874 Hello,I am trying to use my custom dataset ,Could you give some suggestions about handing the coordinate system on sourceloder part and project_human_boxes function?
in project_human_boxes function,i do not use 'opencv2dataset' and 'world2cam = np.linalg.inv(cam2world)' ,maybe you need to calculate 'corners_cam' based on your own extrinsic format.

**Comment by zzz5y** [comment]
> > @xiao1874 Hello,I am trying to use my custom dataset ,Could you give some suggestions about handing the coordinate system on sourceloder part and project_human_boxes function?
> in project_human_boxes function,i do not use 'opencv2dataset' and 'world2cam = np.linalg.inv(cam2world)' ,maybe you need to calculate 'corners_cam' based on your own extrinsic format.

Thanks a lot！I will try it.
