### ISSUE TITLE
A question about pedestrian motion editing.

### ISSUE THREAD

**Issue by MMMaverick** [ziyc/drivestudio#57]
Hello, thank you for your excellent work! I saw on the project page of Drive Studio that you can make pedestrians perform complex actions such as dancing, but I did not see how to achieve this in the code. I have currently completed some simple rigid body editing functions like deletion and replacement using the provided interface functions. If I want to have fine control over pedestrian behavior, what direction should I focus on?

**Comment by TurtleZhong** [comment]
hey,bro! Have you tried this project use your own dataset?

**Comment by MMMaverick** [comment]
@TurtleZhong Hello, I'm planning to do it, but I haven't started yet.
