### ISSUE TITLE
Preprocess the data show error

### ISSUE THREAD

**Issue by happyxuwork** [ziyc/drivestudio#8]
i download the segment-10455472356147194054_1560_000_1580_000_with_camera_labels.tfrecord from https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_4_2/individual_files/training?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22segment-10455472356147194054_5C_22_22%257D%255D%22))&prefix=segment-10455472356147194054&forceOnObjectsSortingFiltering=false and Running the preprocessing script like fellow:python3 datasets/preprocess.py --data_root data/waymo/raw/ --target_dir data/waymo/processed --dataset waymo --split training --scene_ids 23 --workers 1 --process_keys images lidar calib pose dynamic_masks object
but something error occ:
![image](https://github.com/user-attachments/assets/a63ce16e-b85c-4ce5-b607-003ebe66fc77)

**Comment by ziyc** [comment]
Hi @happyxuwork, the waymo_preprocess script gets some strange bugs from `waymo_open_dataset` when workers == 1. Usually I set workers larger than 1. I'll try to fix this, but before that, please try workers > 1 even if you're processing only one scene. It should work.

**Comment by shawnsya** [comment]
I have the same error. Setting workers to 4 doesn't help.

**Comment by happyxuwork** [comment]
@ziyc when i set workers to 2, the error still occ as fellow:
![image](https://github.com/user-attachments/assets/e04fd53f-a27f-4626-9133-d2fc1851207c)

**Comment by ziyc** [comment]
Hi @happyxuwork @shawnsya, This error seems to result from using the wrong Waymo dataset version. Are you downloading the scene flow version of Waymo? 

Please use our script `datasets/waymo/waymo_download.py` to download the scene flow version, or manually download from here: https://console.cloud.google.com/storage/browser/waymo_open_dataset_scene_flow;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

![image](https://github.com/user-attachments/assets/a1737699-e792-4fa0-bb68-0ab1813f1088)

**Comment by happyxuwork** [comment]
@ziyc ok i will try it again and download the right dataset, thanks
