### ISSUE TITLE
diable gsplat accelerator

### ISSUE THREAD

**Issue by zhangSaneC** [ziyc/drivestudio#9]
Hi, thanks for your excellent work.

My card is P100, with compute capability = 6.0, according to link https://github.com/nerfstudio-project/gsplat/issues/226, which says "gsplat requires a modern GPU that has compute capability >= 7.0."

**Is there anyway I can disable gsplat accelerator?** otherwise error occors. Thanks for your reply!

**Comment by ziyc** [comment]
Hi @zhangSaneC, gsplat is not an accelerator, but the rendering kernel for Gaussians. We use gsplat (>=1.0.0) in our system. It cannot be disabled as it's an essential part of the rendering process.

**Comment by zhangSaneC** [comment]
Thanks for your reply.
